/**
 * spool init [--dir <path>] [--force] [--adapter <name>]
 *
 * Scaffolds .spool/ in the current project directory.
 * Analyzes the project to auto-generate steering files.
 */

import { existsSync, cpSync, readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { log, success, error } from "../utils.js";
import { stringifyYaml } from "../core/yaml.js";
import { detectProject } from "../core/detect.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ASSETS_DIR = join(__dirname, "..", "..", ".spool");

export function commandInit(args: string[]): void {
  const targetDir = args.includes("--dir") ? args[args.indexOf("--dir") + 1] : process.cwd();
  const force = args.includes("--force");
  const adapter = args.includes("--adapter") ? args[args.indexOf("--adapter") + 1] : "claude-code";
  const spoolDir = join(targetDir, ".spool");

  if (existsSync(spoolDir) && !force) {
    log(".spool/ already exists. Use --force to overwrite.");
    return;
  }

  if (!existsSync(ASSETS_DIR)) {
    error("Asset directory not found. Reinstall spool.");
    process.exit(1);
  }

  // Copy template
  cpSync(ASSETS_DIR, spoolDir, { recursive: true, force });
  success(`Initialized .spool/ in ${targetDir}`);

  // List what was installed
  const agents = readdirSync(join(spoolDir, "agents")).filter(f => f.endsWith(".yaml"));
  const workflows = readdirSync(join(spoolDir, "workflows")).filter(f => f.endsWith(".yaml"));
  log(`Agents: ${agents.map(f => f.replace(".yaml", "")).join(", ")}`);
  log(`Workflows: ${workflows.map(f => f.replace(".yaml", "")).join(", ")}`);

  // Auto-detect and generate steering
  generateSteering(targetDir, spoolDir);

  // Create spool.yaml if it doesn't exist
  const configPath = join(targetDir, "spool.yaml");
  if (!existsSync(configPath)) {
    const config = {
      version: 1,
      adapter,
      loop: { max_retries: 3, retry_delay: 0 },
      learnings: { auto: true, inject: true },
    };
    writeFileSync(configPath, stringifyYaml(config) + "\n");
    log(`Created spool.yaml (adapter: ${adapter})`);
  }

  log("\nCustomize steering files for your project:");
  log("  .spool/steering/structure.md — your codebase layout");
  log("  .spool/steering/tech.md — your tech stack");
  log("  .spool/steering/product.md — your business context");
}

function generateSteering(projectDir: string, spoolDir: string): void {
  const info = detectProject(projectDir);

  // Tech stack file
  const techLines: string[] = ["# Tech Stack\n", "*Auto-generated by spool init*\n"];

  if (info.language !== "unknown") {
    techLines.push("## Stack\n");
    techLines.push(`- Language: ${info.language}`);
    if (info.framework) techLines.push(`- Framework: ${info.framework}`);
    if (info.buildTool) techLines.push(`- Build: ${info.buildTool}`);
    if (info.testFramework) techLines.push(`- Testing: ${info.testFramework}`);
  }

  const scriptKeys = Object.keys(info.scripts);
  if (scriptKeys.length > 0) {
    techLines.push("\n## Scripts\n");
    const relevant = ["build", "dev", "start", "test", "lint", "format", "typecheck"];
    for (const name of relevant) {
      if (info.scripts[name]) {
        techLines.push(`- \`${name}\`: \`${info.scripts[name]}\``);
      }
    }
  }

  // Structure file
  const structLines: string[] = ["# Project Structure\n", "*Auto-generated by spool init*\n"];

  if (info.directories.length > 0) {
    structLines.push("## Directory Layout\n", "```");
    for (const entry of info.directories) {
      structLines.push(entry);
    }
    structLines.push("```");
  }

  const techDest = join(spoolDir, "steering", "tech.md");
  const structDest = join(spoolDir, "steering", "structure.md");

  if (techLines.length > 3) {
    writeFileSync(techDest, techLines.join("\n") + "\n");
    log("  steering/tech.md (auto-generated from project)");
  }
  if (structLines.length > 3) {
    writeFileSync(structDest, structLines.join("\n") + "\n");
    log("  steering/structure.md (auto-generated from project)");
  }
}
